services:
  forge_1_19_2:
    image: "itzg/minecraft-server"
    container_name: "midas-forge-19"
    ports:
      - "25570:25565"
    volumes:
      - "./forge_1_19_2/mods:/mods"
      - "./forge_1_19_2/data:/data"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.19.2"
    tty: true
    stdin_open: true
    restart: always
  forge_1_20_1:
    image: "itzg/minecraft-server"
    container_name: "midas-forge-20"
    ports:
      - "25571:25565"
    volumes:
      - "./forge_1_20_1/mods:/mods"
      - "./forge_1_20_1/data:/data"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
    tty: true
    stdin_open: true
    restart: always
  paper_1_20_1:
    image: "itzg/minecraft-server"
    container_name: "midas-paper-20"
    ports:
      - "25572:25565"
    volumes:
      - "./paper_1_20_1/plugins:/plugins"
      - "./paper_1_20_1/data:/data"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.20.1"
    tty: true
    stdin_open: true
    restart: always